version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 20

  customer-service:
    build: ./customer-service
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_DATABASE: customers_db
      KAFKA_BROKERS: "98.88.99.206:9092,34.195.107.7:9092,54.221.160.63:9092"
      KAFKA_TOPIC: vdodia.customer.evt
    depends_on:
      db:
        condition: service_healthy

  book-service:
    build: ./book-service
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
      MYSQL_DATABASE: books_db
      RECOMMENDATION_SERVICE_URL: http://recommendation-engine:8080
    depends_on:
      db:
        condition: service_healthy

  internal-alb:
    image: nginx:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./test_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customer-service
      - book-service

  web-bff:
    build: ./web-bff
    ports:
      - "8081:80"
    environment:
      URL_BASE_BACKEND_SERVICES: http://internal-alb:3000
    depends_on:
      - internal-alb

  mobile-bff:
    build: ./mobile-bff
    ports:
      - "8082:80"
    environment:
      URL_BASE_BACKEND_SERVICES: http://internal-alb:3000
    depends_on:
      - internal-alb

  recommendation-engine:
    image: pmerson/book-recommendations-ms
    command: ["--delay=0"]
    ports:
      - "9090:8080"

  crm-service:
    build: ./crm-service
    environment:
      KAFKA_BROKERS: "98.88.99.206:9092,34.195.107.7:9092,54.221.160.63:9092"
      KAFKA_TOPIC: vdodia.customer.evt
      EMAIL_PROVIDER: gmail
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      ANDREW_ID: vdodia
    depends_on:
      - customer-service
