apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: bookstore-ns
  labels:
    app: customer-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/bookstore/customer-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: host
            - name: DATABASE_PORT
              value: "3306"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: MYSQL_DATABASE
              value: customers_db
            - name: KAFKA_BROKERS
              value: "98.88.99.206:9092,34.195.107.7:9092,54.221.160.63:9092"
            - name: KAFKA_TOPIC
              value: vdodia.customer.evt
          livenessProbe:
            httpGet:
              path: /status
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
